### Binary Image Classification 

In [1]:
from tensorflow import keras
import matplotlib.pyplot as plt
from tqdm import tqdm
import random
import pickle
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten

In [2]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.utils import to_categorical
from keras.preprocessing import image
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from tqdm import tqdm
#from PIL import ImageEnhance
#from PIL import Image as pil_image

Using TensorFlow backend.


In [3]:
train=pd.read_csv('book10.csv')

In [4]:
train.head()

Image_Name  Lable
0       H(0)      0
1       H(1)      0
2       H(2)      0
3       H(3)      0
4       H(4)      0

In [5]:
train.shape

(9258, 2)

In [6]:
train.shape[0]

9258

In [7]:
train['Image_Name'].iloc[0]

'H(0)'

In [8]:
for i in range (5):
     print(train['Image_Name'].iloc[i])

H(0)
H(1)
H(2)
H(3)
H(4)


In [9]:
train_image =[]
for i in  tqdm(range(train.shape[0])):
        img = image.load_img('10\\'+'H('+str(i)+')'+'.jpg', target_size=(28,28,1 ) , grayscale=True )
        img = image.img_to_array(img)
        img = img/255
        train_image.append(img)
       # img = image.load_img('10/'+train['Image_Name'][i]+'.jpg' ,

  0%|                                                                                         | 0/9258 [00:00<?, ?it/s]c:\users\sahhay\appdata\local\programs\python\python37\lib\site-packages\keras_preprocessing\image\utils.py:104: UserWarning: grayscale is deprecated. Please use color_mode = "grayscale"
  warnings.warn('grayscale is deprecated. Please use '
100%|██████████████████████████████████████████████████████████████████████████████| 9258/9258 [03:41<00:00, 41.88it/s]


In [10]:
X = np.array(train_image)
y=train['Lable'].values

In [11]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [12]:
class_names=['healthy','unhealthy']

In [13]:
class_names[y[1000]]

'healthy'

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

In [15]:
print("X shape is:          " , X.shape , "\n",
      'X_train shape is:   ' , X_train.shape,"\n" 
      ,"X test shape is    " , X_test.shape,"\n"
      ,'y_train shape is:   ' ,y.shape )

X shape is:           (9258, 28, 28, 1) 
 X_train shape is:    (7406, 28, 28, 1) 
 X test shape is     (1852, 28, 28, 1) 
 y_train shape is:    (9258,)


In [16]:
y_train

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [17]:
uniqueValues = train['Lable'].unique()
print(uniqueValues)

[0 1]


In [18]:
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.layers import BatchNormalization
import random
from keras.regularizers import l1 , l2

## Model

In [34]:
model = Sequential()
model.add(Flatten(input_shape=(28,28,1)))
model.add(Dense(40, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(2, activation='softmax'))


In [35]:
#compile with loss func and accu
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [38]:
model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test),batch_size=32)

Train on 7406 samples, validate on 1852 samples
Epoch 1/5
7406/7406 [==============================] - 1s 167us/step - loss: 0.1978 - accuracy: 0.9157 - val_loss: 0.2754 - val_accuracy: 0.8656
Epoch 2/5
7406/7406 [==============================] - 1s 169us/step - loss: 0.1951 - accuracy: 0.9156 - val_loss: 0.2600 - val_accuracy: 0.8828
Epoch 3/5
7406/7406 [==============================] - 1s 166us/step - loss: 0.1889 - accuracy: 0.9176 - val_loss: 0.2586 - val_accuracy: 0.8871
Epoch 4/5
7406/7406 [==============================] - 1s 164us/step - loss: 0.1798 - accuracy: 0.9218 - val_loss: 0.2394 - val_accuracy: 0.8958
Epoch 5/5
7406/7406 [==============================] - 1s 152us/step - loss: 0.1713 - accuracy: 0.9309 - val_loss: 0.2366 - val_accuracy: 0.9017


In [39]:
model.evaluate(X_test, y_test)

1852/1852 [==============================] - 0s 55us/step


[0.23657743191873537, 0.9017278552055359]

In [40]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_4 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_11 (Dense)             (None, 40)                31400     
_________________________________________________________________
dense_12 (Dense)             (None, 20)                820       
_________________________________________________________________
dense_13 (Dense)             (None, 10)                210       
_________________________________________________________________
dense_14 (Dense)             (None, 2)                 22        
Total params: 32,452
Trainable params: 32,452
Non-trainable params: 0
_________________________________________________________________


## Load test data

In [83]:
test = pd.read_csv('test.csv')

In [84]:
test.head()

test_file  test_lable
0   test(1)           0
1   test(2)           0
2   test(3)           0
3   test(4)           0
4   test(5)           0

In [22]:
test.shape

(2349, 2)

In [111]:
#number of difrent classesin test set
test["test_lable"].value_counts()

1    2085
0     264
Name: test_lable, dtype: int64

In [104]:
test_image =[]
for i in  tqdm(range(test.shape[0])):
        img = image.load_img('test_set\\'+'test('+str(i)+')'+'.jpg', target_size=(28,28))
        img = image.img_to_array(img)
        img = img/255
        test_image.append(img)
#test = np.array(test_image)

100%|█████████████████████████████████████████████████████████████████████████████| 2349/2349 [00:03<00:00, 588.92it/s]


In [105]:
x_test911= np.array(test_image)
y_test911=test['test_lable'].values

In [88]:
# making predictions
prediction = model.predict(x_test911)

In [106]:
X_new = x_test911[1:10]
y_proba = model.predict(X_new)
y_proba.round(2)

array([[0.  , 1.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.99, 0.01, 0.  , 0.  , 0.  ],
       [0.  , 0.83, 0.17, 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.98, 0.02, 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.99, 0.01, 0.  , 0.  , 0.  ],
       [0.  , 0.93, 0.07, 0.  , 0.  , 0.  ],
       [0.  , 0.97, 0.03, 0.  , 0.  , 0.  ]], dtype=float32)

In [90]:
y_predict = model.predict_classes(X_new)
y_predict

array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [107]:
x_new1 = x_test911[1:30]
x_new2 = x_test911[1000:1030]
y_prob1 = model.predict(x_new1)
y_prob2 = model.predict(x_new2)

In [108]:
y_pred1 = model.predict_classes(x_new1)
y_pred2 = model.predict_classes(x_new2)

In [109]:
print((class_names)[y_test911[1]],'       ',y_pred1,"\n"
          ,(class_names)[y_test911[1000]],'  ',y_pred2)

healthy         [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 2 1 1 1 1 2 1 1] 
 unhealthy    [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2]


In [110]:
score = model.evaluate(x_test911, y_test911, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

Test score: 12.734881541535112
Test accuracy: 0.010642826557159424


In [102]:
score = model.evaluate(X_test, y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

Test score: 0.050027043890553985
Test accuracy: 0.9816414713859558
