# MNIST Classification with a Fully-Connected Neural Network
## Sequential Model network of Dense layers for training MNIST Dataset

In [23]:
from keras import models
from keras.layers import Dense
from keras.utils import to_categorical
from keras.datasets import mnist
from IPython.display import SVG

## Load  dataset MNIST

In [25]:
# Load data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Check state of dataset
data_summary(X_train, y_train, X_test, y_test)

Train images shape: (60000, 28, 28)
Train labels shape: (60000,)
Test images shape: (10000, 28, 28)
Test labels shape: (10000,)
Train labels: [5 0 4 ... 5 6 8]
Test labels: [7 2 1 ... 4 5 6]


## Reshape data

In [26]:
# Reshape data
X_train = X_train.reshape((X_train.shape[0], 28 * 28))
X_train = X_train.astype('float32') / 255
X_test = X_test.reshape((X_test.shape[0], 28 * 28))
X_test = X_test.astype('float32') / 255

# Categorically encode labels
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# Check state of dataset
data_summary(X_train, y_train, X_test, y_test)

Train images shape: (60000, 784)
Train labels shape: (60000, 10)
Test images shape: (10000, 784)
Test labels shape: (10000, 10)
Train labels: [[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
Test labels: [[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## Build the sequential model

In [49]:
model = models.Sequential()
model.add(Dense(256, activation='relu', input_shape=(28 * 28,)))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))


In [50]:
# Compile model
model.compile(optimizer='sgd',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [55]:
# Train model
model.fit(X_train, y_train,
          batch_size=128,
          epochs=5,
          verbose=1,
          validation_data=(X_test, y_test))

Epoch 1/5
469/469 [==============================] - 3s 6ms/step - loss: 0.1515 - accuracy: 0.9571 - val_loss: 0.1545 - val_accuracy: 0.9528
Epoch 2/5
469/469 [==============================] - 3s 7ms/step - loss: 0.1470 - accuracy: 0.9585 - val_loss: 0.1494 - val_accuracy: 0.9546
Epoch 3/5
469/469 [==============================] - 3s 7ms/step - loss: 0.1427 - accuracy: 0.9600 - val_loss: 0.1451 - val_accuracy: 0.9565
Epoch 4/5
469/469 [==============================] - 3s 6ms/step - loss: 0.1386 - accuracy: 0.9612 - val_loss: 0.1427 - val_accuracy: 0.9568
Epoch 5/5
469/469 [==============================] - 3s 7ms/step - loss: 0.1344 - accuracy: 0.9627 - val_loss: 0.1396 - val_accuracy: 0.9584


In [56]:
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.1396455615758896
Test accuracy: 0.9584000110626221


In [57]:
# Summary of neural network
model.summary()

Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_40 (Dense)            (None, 256)               200960    
                                                                 
 dense_41 (Dense)            (None, 128)               32896     
                                                                 
 dense_42 (Dense)            (None, 10)                1290      
                                                                 
Total params: 235,146
Trainable params: 235,146
Non-trainable params: 0
_________________________________________________________________
